### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by apyxpi** [Nyxonn/gb_banking#1]
Is it possible to provide an english version of the script? 

Thank you in advance

**Comment by yungleanio** [comment]
> Is it possible to provide an english version of the script? 
> 
> Thank you in advance

Yes, just fucking translate it nibber, bruh, big chungus moment

**Comment by apyxpi** [comment]
> > Is it possible to provide an english version of the script?
> > Thank you in advance
> 
> Yes, just fucking translate it nibber, bruh, big chungus moment

Thank you for your good words......

**Comment by yungleanio** [comment]
> > > Is it possible to provide an english version of the script?
> > > Thank you in advance
> > 
> > 
> > Yes, just fucking translate it nibber, bruh, big chungus moment
> 
> Thank you for your good words......

No problem, maybe beside translating this script for you my king should I make you blowjob too?

**Comment by Nyxonn** [comment]
Will be translated with an update
